{
    'name': 'Open HRMS Custody',
    'version': '18.0.1.0.0',
    'category': 'Human Resources',
    'summary': """Manage the company properties""",
    'description': 'Manage the company properties when it is in '
                   'the custody of an employee',
    'author': 'Cybrosys Techno solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': "https://www.cybrosys.com",
    'depends': ['hr', 'mail', 'base'],  # Removed hr_employee_updation for now
    'data': [
        'security/custody_security.xml',
        'security/ir.model.access.csv',
        'data/custody_sequence_data.xml',
        'data/ir_cron_data.xml',
        'data/mail_custody_notification_data.xml',
        'wizard/property_return_reason_views.xml',
        'wizard/property_return_date_views.xml',
        'views/hr_custody_views.xml',
        'views/custody_property_views.xml',
        'views/hr_employee_views.xml',
        'reports/report_custody_views.xml',
    ],
    'demo': ['data/demo_data.xml'],
    'images': ['static/description/banner.jpg'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
